title: Sparsh N
url: "https://sparsh-n.github.io"
baseurl: ""

markdown: kramdown
tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
